<?php

namespace Database\Seeders;

use App\Models\Game;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        Game::create(['name' => 'لون حسب الرقم', 'template_url' => 'color_by_number']);
        Game::create(['name' => 'اسحب والصق', 'template_url' => 'drag&drop']);
        Game::create(['name' => 'سباق الأرقام', 'template_url' => 'number_race']);
        Game::create(['name' => 'مقارنة الأعداد', 'template_url' => 'compare_numbers']);
        Game::create(['name' => 'التمساح الجائع', 'template_url' => 'hungry_corcodile']);
        Game::create(['name' => 'رتب الأرقام حسب الأيقونات', 'template_url' => 'sort_icons']);
        Game::create(['name' => '2 سباق الأرقام', 'template_url' => 'number_race2']);
        Game::create(['name' => 'صيد الأرقام', 'template_url' => 'numbers_hunting']);
        Game::create(['name' => 'سباق الأرنب', 'template_url' => 'rabbit_race']);
        Game::create(['name' => 'سلم الحيوانات', 'template_url' => 'animals_lader']);
        Game::create(['name' => 'من بالصف ؟؟', 'template_url' => 'who_is_in_line']);
        Game::create(['name' => 'موقف السيارات الفارغ', 'template_url' => 'empty_parking']);
        Game::create(['name' => 'السلة الفارغة', 'template_url' => 'empty_pasket']);
        Game::create(['name' => 'بالونات الجمع', 'template_url' => 'ballon_sum']);
        Game::create(['name' => 'فقاعات الجمع', 'template_url' => 'bubble_sum']);
        Game::create(['name' => 'شبكة الأسماك', 'template_url' => 'fish_net']);
        Game::create(['name' => 'سباق الجمع', 'template_url' => 'race_sum']);
        Game::create(['name' =>'الأرانب في الحديقة', 'template_url' => 'rabbits_in_the_garden']);
        Game::create(['name' => 'تحويل العمليات بالتفاح', 'template_url' => 'apples_convert']);
        Game::create(['name' => 'عملية الجمع الناقصة', 'template_url' => 'missing_add']);
        Game::create(['name' => 'مصنع الأرقام', 'template_url' => 'numbers_factory']);
        Game::create(['name' => 'سباق المضاعفات', 'template_url' => 'race_multiples']);
        Game::create(['name' => 'انقر للعد', 'template_url' => 'click_to_count']);
        Game::create(['name' => 'بالونات المضاعفات', 'template_url' => 'ballons_multiples']);
        Game::create(['name' => 'قطار الأرقام', 'template_url' => 'numbers_train']);
        Game::create(['name' => 'فقاعات الأرقام', 'template_url' => 'numbers_bubbles']);
        Game::create(['name' => 'مقارنة الصور', 'template_url' => 'compare_images']);
        Game::create(['name' => 'ميزان الأرقام', 'template_url' => 'number_scales']);
        Game::create(['name' => 'رتيب تصاعدياً وتنازلياً', 'template_url' => 'sort_asce_desc']);
        Game::create(['name' => 'سلم الأرقام', 'template_url' => 'number_lader']);
        Game::create(['name' => 'ترتيب الأرقام', 'template_url' => 'sort_numbers']);
        Game::create(['name' => 'مجموعات الكعك', 'template_url' => 'cakes_pair']);
        Game::create(['name' => 'العدد التالي', 'template_url' => 'next_number']);
        Game::create(['name' => 'سباق الأعداد 3', 'template_url' =>'numbers_race']);
        Game::create(['name' => '2 مقارنة الأعداد', 'template_url' => 'compare_game']);
        Game::create(['name' => 'ترتيب الأعداد', 'template_url' => 'sort_numbers_game']);
        Game::create(['name' => '2 ترتيب الأعداد', 'template_url' => 'arrange']);
        Game::create(['name' => 'اسحب وأفلت', 'template_url' => 'place_value_game']);
        Game::create(['name' => 'اختر القيمة المنزلية', 'template_url' => 'place_value_game1']);
        Game::create(['name' => 'حدد زوجي أم فردي', 'template_url' => 'oddandeven']);
        Game::create(['name' => 'صيد الأعداد الزوجية', 'template_url' => 'rev']);
        Game::create(['name' => 'اختر الاجابة الصحيحة', 'template_url' => 'add']);
        Game::create(['name' => 'تحدي الجمع السريع', 'template_url' => 'add2']);
        Game::create(['name' => '2 اختر الاجابة الصحيحة', 'template_url' => 'sub']);
        Game::create(['name' => 'قارن بين الأعداد', 'template_url' => 'number']);
        Game::create(['name' => 'رتب تنازلياً', 'template_url' => 'arrange2']);
        Game::create(['name' => 'حدد نوع الخط', 'template_url' => 'lesson1_2']);
        Game::create(['name' => 'جد المربع', 'template_url' => 'lesson2_2']);
        Game::create(['name' => 'سلة التفاح', 'template_url' => 'apples_basket']);
        Game::create(['name' => 'البطريق يصطاد الأسماك', 'template_url' => 'penguin']);
        Game::create(['name' => 'سلة العملات', 'template_url' => 'coins']);
        Game::create(['name' => 'البطاقات التعليمية', 'template_url' => 'cards']);
        Game::create(['name' => 'فصل الأرقام', 'template_url' => 'numbers_splitting']);
        Game::create(['name' => 'البازل الموسعة', 'template_url' => 'puzzle']);
        Game::create(['name' => 'الفراشات والزهور', 'template_url' => 'flowers']);
        Game::create(['name' => 'الكرات الملونة', 'template_url' => 'colored_balls']);
        Game::create(['name' => 'احسب معي 1', 'template_url' => 'lesson1']);
        Game::create(['name' => 'احسب معي 2', 'template_url' => 'lesson2']);
        Game::create(['name' => 'احسب معي 3', 'template_url' => 'lesson3']);
        Game::create(['name' => 'احسب معي 4', 'template_url' => 'lesson4']);
        Game::create(['name' => 'احسب معي 5', 'template_url' => 'lesson5']);
        Game::create(['name' => 'احسب معي 6', 'template_url' => 'lesson6']);
        Game::create(['name' => 'احسب معي 7', 'template_url' => 'lesson8']);
        Game::create(['name' => 'احسب معي 8', 'template_url' => 'lesson9']);
        Game::create(['name' => 'احسب معي 9', 'template_url' => 'lesson10']);
        Game::create(['name' => 'احسب معي 10', 'template_url' => 'lesson11']);
        Game::create(['name' => 'احسب معي 11', 'template_url' => 'lesson12']);
        Game::create(['name' => 'احسب معي 12', 'template_url' => 'lesson13']);
        Game::create(['name' => 'احسب معي 13', 'template_url' => 'lesson14']);
        Game::create(['name' => 'هل هو خط مستقيم أم منحني ؟', 'template_url' => 'lesson1_1']);
        Game::create(['name' => 'أين المربع؟', 'template_url' => 'lesson2_2']);
        Game::create(['name' => 'رتب حسب المطلوب', 'template_url' => 'rearrange']);
        Game::create(['name' => 'مقارنة الأعداد 2', 'template_url' => 'compare_numbers2']);
        Game::create(['name' => 'بناء الأعداد', 'template_url' => 'numbers_building']);
        Game::create(['name' => 'تفكيك القيمة المنزلية', 'template_url' => 'split']);
        Game::create(['name' => 'اكتب القيمة المنزلية', 'template_url' => 'write_place_value']);

        Game::create(['name' => 'سباق القيمة المنزلية', 'template_url' => 'place_value_race']);
        Game::create(['name' => 'قياس القيمة المنزلية', 'template_url' => 'measure_place_value']);
        Game::create(['name' => 'فرز الأعداد', 'template_url' => 'rearrange2']);
        Game::create(['name' => 'مبارزة البطاقات', 'template_url' => 'cards_battle']);
        Game::create(['name' => 'صوب للتقريب', 'template_url' => 'close']);
        Game::create(['name' =>'الجمع العمودي','template_url' => 'col_sum']);
        Game::create(['name' => 'سلة الجمع', 'template_url' => 'sum_pasket']);
        Game::create(['name' => 'الجمع العمودي مع الحمل', 'template_url' => 'col_sum_with']);
        Game::create(['name' => 'سلم الجمع مع الحمل', 'template_url' => 'sum_lader_with_carry']);
        Game::create(['name' => 'اطرح مع الاستلاف', 'template_url' => 'with']);
        Game::create(['name' => 'اطرح بدون استلاف', 'template_url' => 'without']);
        Game::create(['name' => 'قرب ضمن 9999', 'template_url' => 'near']);
        Game::create(['name' => 'احسب المحيط', 'template_url' => 'dim']);
        Game::create(['name' => 'بنغو الجمع', 'template_url' => 'bingo']);
        Game::create(['name' => 'اختبار المدقق الرياضي', 'template_url' => 'exam_calc']);
        Game::create(['name' => 'تحدي الجمع والطرح بالتوقيت', 'template_url' => 'first']);
        Game::create(['name' => 'محقق الأرقام', 'template_url' => 'numbers_detective']);
        Game::create(['name' => 'المتاهة السريعة', 'template_url' => 'quick_maze']);
        Game::create(['name' => 'نافذة المحايد', 'template_url' => 'window']);
        Game::create(['name' => 'مطابقة المرايا', 'template_url' => 'mirrors']);
        Game::create(['name' => 'املأ الفراغ', 'template_url' => 'mul']);
        Game::create(['name' => 'املأ الفراغ 2', 'template_url' => 'mul2']);
        Game::create(['name' => 'توزيع المهام', 'template_url' => 'div1']);
        Game::create(['name' => 'عائلة الضرب', 'template_url' => 'div2']);
        Game::create(['name' => 'برج الكسور', 'template_url' => 'tower']);
        Game::create(['name' => 'مكافئ الكسر العشوائي', 'template_url' => 'random']);
        Game::create(['name' => 'مطابقة الكسور المكافئة', 'template_url' => 'memory']);
        Game::create(['name' => 'الميزان الرقمي', 'template_url' => 'scale']);
        Game::create(['name' => 'صياد المجسمات', 'template_url' => 'hunter']);
        Game::create(['name' => 'الصياد الذكي', 'template_url' => 'hunter2']);
        Game::create(['name' => 'بناء', 'template_url' => 'units_scale']);
        Game::create(['name' => 'ساعة التحويل', 'template_url' => 'hour']);
        Game::create(['name' => 'مخزون القياس', 'template_url' => 'box']);
        Game::create(['name' => 'مهمة التقدير', 'template_url' => 'mission']);
        Game::create(['name' => 'باني الوحدات المربعة', 'template_url' => 'builder']);
        Game::create(['name' => 'جد المحيط', 'template_url' => 'dim']);
        Game::create(['name' => 'احسب ناتج الضرب', 'template_url' => 'mul1']);

        Game::create(['name' => 'مطاردة الأعداد العملاقة', 'template_url' => 'chaser']);
        Game::create(['name' => 'مصنع الأعداد الذكي', 'template_url' => 'factory']);
        Game::create(['name' => 'مقارنة الكنز', 'template_url' => 'treasure']);
        Game::create(['name' => 'ترتيب الكنوز', 'template_url' => 'rea_tre']);
        Game::create(['name' => 'معركة الأعداد العملاقة', 'template_url' => 'battle']);
        Game::create(['name' => 'برج المقارنة الذكي', 'template_url' => 'tower2']);
        Game::create(['name' => 'مصنع الضرب السريع', 'template_url' => 'factory2']);
        Game::create(['name' => 'تحدي الضرب الذهني', 'template_url' => 'challenge']);
        Game::create(['name' => 'مملكة القسمة السحرية', 'template_url' => 'queendom']);
        Game::create(['name' => 'مصنع القسمة الذكي', 'template_url' => 'factory3']);
        Game::create(['name' => 'ساعة التقدير الذكية', 'template_url' => 'watch']);
        Game::create(['name' => 'مختبر التقدير الذكي', 'template_url' => 'lab']);
        Game::create(['name' => '2 مطابقة الكسور المكافئة', 'template_url' => 'with1']);
        Game::create(['name' => 'باحث الكسور المفقودة', 'template_url' => 'finder']);
        Game::create(['name' => 'حديقة الكسور الملونة', 'template_url' => 'garden']);
        Game::create(['name' => 'مطابقة كعكات الكسور', 'template_url' => 'cakes']);
        Game::create(['name' => 'مطابقة الكسور', 'template_url' => 'with2']);
        Game::create(['name' => 'مصفوفة الكسور', 'template_url' => 'matrix']);
        Game::create(['name' => 'مستكشف الأعداد الكسرية', 'template_url' => 'discover']);
        Game::create(['name' => 'مختبر الأعداد الكسرية', 'template_url' => 'lab2']);
        Game::create(['name' => 'مزرعة الأعداد الكسرية', 'template_url' => 'farm']);
        Game::create(['name' => 'مختبر الأعداد الكسرية 2', 'template_url' => 'lab3']);
        Game::create(['name' => 'بازل المستقيمات المتعامدة', 'template_url' => 'lines_puzzle']);
        Game::create(['name' => 'صائد المستقيمات المتوازية', 'template_url' => 'lines_hunter']);
        Game::create(['name' => 'مستكشف الزوايا', 'template_url' => 'angle_discover']);
        Game::create(['name' => 'صائد الزوايا', 'template_url' => 'angles_hunter']);
        Game::create(['name' => 'مستكشف زوايا المثلث', 'template_url' => 'angles_discover']);
        Game::create(['name' => 'بازل تصنيف المثلثات', 'template_url' => 'angles_puzzle']);
        Game::create(['name' => 'مصنع المضاعفات', 'template_url' => 'factory4']);
        Game::create(['name' => 'مطاردة المضاعفات', 'template_url' => 'chase']);
        Game::create(['name' => 'صائد الأعداد القابلة للقسمة', 'template_url' => 'hunter3']);
        Game::create(['name' => 'ساحة القسمة', 'template_url' => 'class']);
        Game::create(['name' => 'مصنع الضرب الذكي', 'template_url' => 'factory5']);
        Game::create(['name' => 'تحدي الضرب السريع', 'template_url' => 'challenge2']);
        Game::create(['name' => 'بطل القسمة الممتعة', 'template_url' => 'hero']);
        Game::create(['name' => 'مصنع القسمة الذكي 2', 'template_url' => 'factory6']);
        Game::create(['name' => 'مغامرة الكسور العشرية', 'template_url' => 'adventure1']);
        Game::create(['name' => 'سوق الكسور العشرية', 'template_url' => 'market']);
        Game::create(['name' => 'مغامرة الأعداد العشرية', 'template_url' => 'adventure']);
        Game::create(['name' => 'مدينة الأعداد العشرية', 'template_url' => 'city']);
        Game::create(['name' => 'مصنع الكسور العشرية', 'template_url' => 'factory7']);
        Game::create(['name' => 'سباق الكسور العشرية', 'template_url' => 'race']);
        Game::create(['name' => 'مغامرة جمع وطرح الكسور العشرية', 'template_url' => 'adventure2']);
        Game::create(['name' => 'ساحة التحدي العشري', 'template_url' => 'ground']);
        Game::create(['name' => 'مستكشف خصائص المربع', 'template_url' => 'discover1']);
        Game::create(['name' => 'باني المربعات المحترف', 'template_url' => 'builder1']);
        Game::create(['name' => 'مستكشف محيط المربع', 'template_url' => 'discover2']);
        Game::create(['name' => 'بازل محيط المربع', 'template_url' => 'puzzle1']);
        Game::create(['name' => 'مملكة المستطيلات', 'template_url' => 'kingdom']);
        Game::create(['name' => 'تحدي المستطيلات', 'template_url' => 'challenge3']);
        Game::create(['name' => 'مستكشف محيط المستطيل', 'template_url' => 'discover3']);
        Game::create(['name' => 'مهندس محيط المستطيل', 'template_url' => 'eng']);
        Game::create(['name' => 'ساحر التحويلات', 'template_url' => 'magic']);
        Game::create(['name' => 'مصنع التحويلات', 'template_url' => 'fac']);
        Game::create(['name' => 'مصنع الحجوم', 'template_url' => 'factory8']);
        Game::create(['name' => 'مستكشف حجم متوازي المستطيلات', 'template_url' => 'dis']);
        Game::create(['name' => 'مختبر التجارب العشوائية', 'template_url' => 'lab1']);
        Game::create(['name' => 'صندوق المفاجآت العشوائي', 'template_url' => 'rand']);
        Game::create(['name' => 'دولاب الحظ العشوائي', 'template_url' => 'wheel']);
        Game::create(['name' => 'مملكة الفرص', 'template_url' => 'king']);
        Game::create(['name' => 'مغامرة الفرص', 'template_url' => 'adven']);
    }
}
