<?php

namespace Database\Seeders;

use App\Models\Lesson;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LessonSeeder extends Seeder
{
    public function run(): void
    {
        Lesson::create(['name' => 'الأعداد من 1-9','unit_id' => 1, 'description' => 'تعلم الأعداد من 1 إلى 9 وكيفية كتابتها وقراءتها','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/الاعداد 1-9.pdf']);
        Lesson::create(['name' => 'مقارنة الأعداد من 1-9','unit_id' => 2, 'description' => 'تعلم كيفية مقارنة الأعداد من 1 إلى 9 باستخدام علامات أكبر من وأصغر من ومتساوي','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/مقارنة الأعداد من 1 إلى 9.pdf']);
        Lesson::create(['name' => 'الترتيب التصاعدي والتنازلي ضمن 9','unit_id' => 2, 'description' => 'تعلم كيفية ترتيب الأعداد من 1 إلى 9 بترتيب تصاعدي وتنازلي','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/الترتيب التصاعدي والتنازلي ضمن 9.pdf']);
        Lesson::create(['name' => 'العدد السابق والتالي ضمن 9','unit_id' => 2, 'description' => 'تعلم كيفية تحديد العدد السابق والتالي لأي عدد من 1 إلى 9','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/العدد السابق والتالي من 1 إلى 9.pdf']);
        Lesson::create(['name' => 'العدد الترتيبي','unit_id' => 2, 'description' => 'تعلم الأعداد الترتيبية من الأول إلى التاسع وكيفية استخدامها','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/العدد الترتيبي.pdf']);
        Lesson::create(['name' => 'العدد صفر','unit_id' => 3, 'description' => 'تعلم مفهوم العدد صفر ودوره في النظام العددي','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/العدد صفر.pdf']);
        Lesson::create(['name' => 'مكونات الأعداد ضمن 9','unit_id' => 3, 'description' => 'تعلم كيفية تحليل الأعداد من 1 إلى 9 إلى مكوناتها الأساسية','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/مكونات الأعداد ضمن 9.pdf']);
        Lesson::create(['name' => 'الجمع ضمن العدد 9','unit_id' => 3, 'description' => 'تعلم كيفية جمع الأعداد من 1 إلى 9 بطريقة سهلة وممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/الجمع ضمن العدد 9.pdf']);
        Lesson::create(['name' => 'الطرح ضمن العدد 9','unit_id' => 3, 'description' => 'اكتشف كيف نطرح الأرقام من 1 إلى 9 خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/الطرح ضمن العدد 9.pdf']);
        Lesson::create(['name' => 'العلاقة بين الجمع والطرح ضمن 9','unit_id' => 4, 'description' => 'تعلم فهم كيف الجمع والطرح مرتبطان ببعضهما البعض ','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/العلاقة بين الجمع والطرح ضمن 9.pdf']);
        Lesson::create(['name' => 'مكونات العدد 10','unit_id' => 5, 'description' => 'اكتشف أسرار الرقم 10 وكيفية تكوينه','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/مكونات العدد 10.pdf']);
        Lesson::create(['name' => 'الأعداد من 11 إلى 19','unit_id' => 5,'description'=>'تعرف على الأرقام بعد العشرة بطريقة مبسطة - من 11 إلى 19','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/الأعداد من 11-19.pdf']);
        Lesson::create(['name' => 'مكونات العدد 20','unit_id' => 5, 'description' => 'اكتشف مكونات الرقم 20 وكيفية تكوينه من أجزاء أصغر','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem1/مكونات العدد 20.pdf']);

        Lesson::create(['name' => ' العدد السابق والتالي','unit_id' => 6, 'description' => 'تعلّم ما هو الرقم الذي يسبق ويلي كل عدد','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/العدد السابق والتالي.pdf']);
        Lesson::create(['name' => 'المقارنة بين عددين','unit_id' => 6, 'description' => 'اكتشف أي رقم أكبر وأي رقم أصغر بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/المقارنة بين عددين.pdf']);
        Lesson::create(['name' => 'الترتيب التصاعدي','unit_id' => 6, 'description' => 'رتب الأرقام من الأصغر إلى الأكبر بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الترتيب التصاعدي.pdf']);
        Lesson::create(['name' => 'الترتيب التنازلي','unit_id' => 6, 'description'=> 'رتب الأرقام من الأكبر إلى الأصغر خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الترتيب التنازلي.pdf']);
        Lesson::create(['name' => 'الفيمة المنزلية','unit_id' => 6, 'description'=> 'تعرف على قيمة الرقم في كل منزلة (الوحدات والعشرات)','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/القيمة المنزلية.pdf']);
        Lesson::create(['name' => 'الصورة الموسعة','unit_id' => 6, 'description'=> 'اكشف الأرقام بشكل مفكك لتفهمها بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الصورة الموسعة.pdf']);
        Lesson::create(['name' => 'الجمع ضمن 10','unit_id' => 7, 'description'=> 'تعلم كيف تجمع الأرقام حتى 10 بطريقة سهلة وممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الجمع ضمن 10.pdf']);
        Lesson::create(['name' => 'الجمع ضمن 18','unit_id' => 7, 'description'=> 'اكتشف الجمع للأرقام حتى 18 بأسلوب مبسط','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الجمع ضمن 18.pdf']);
        Lesson::create(['name' => 'الطرح ضمن 10','unit_id' => 8, 'description'=> 'تعلم الطرح للأرقام حتى 10 بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الطرح ضمن 10.pdf']);
        Lesson::create(['name' => 'الطرح ضمن 18','unit_id' => 8, 'description'=> 'اكتشف الطرح للأرقام حتى 18 خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الطرح ضمن 18.pdf']);
        Lesson::create(['name' => 'العلاقة بين الجمع والطرح','unit_id' => 8, 'description'=> 'فهم كيف أن الجمع والطرح مرتبطان ببعض','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/العلاقة بين الجمع والطرح - الفصل الثاني.pdf']);
        Lesson::create(['name' => 'الأعداد من 21-29','unit_id' => 8, 'description'=> 'تعرّف على الأرقام بين 21 و29 بطريقة مبسطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الاعداد ضمن 21-29.pdf']);
        Lesson::create(['name' => 'الأعداد من 30-90','unit_id' => 8, 'description'=> 'اكتشف الأرقام الكبيرة من 30 إلى 90 بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/الاعداد من 30 - 99.pdf']);
        Lesson::create(['name' => 'مضاعفات العدد 10','unit_id' => 8, 'description'=> 'تعلّم العد بالمضاعفات للعدد 10 بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 1/sem2/مضاعفات العدد 10.pdf']);

        Lesson::create(['name' => 'المقارنة بين عددين','unit_id' => 9,'description'=>'اكتشف أي رقم أكبر وأي رقم أصغر بسهولة','video_url'=>'https://www.youtube.com/embed/VULDqSFsy0M?si=p0YXuByzSaWvY6IZ', 'pdf_path'=>'pdf/grade 2/sem1/المقارنة بين عددين.pdf']);
        Lesson::create(['name' => 'ترتيب الأعداد ضمن 99','unit_id' => 9,'description'=>'رتب الأرقام من الأصغر للأكبر والعكس ضمن 99','video_url'=>'https://youtu.be/fhnaLQyFLqk?si=hr4mL9X2gl6lCOYr', 'pdf_path'=>'pdf/grade 2/sem1/ترتيب الأعداد ضمن 99.pdf']);
        Lesson::create(['name' => 'القيمة المنزلية','unit_id' => 9,'description'=>'تعرّف على قيمة كل رقم حسب مكانه (الوحدات والعشرات)','video_url'=>'https://youtu.be/rO6gq6yxHTQ?si=iZErD37a9IbdcXwz', 'pdf_path'=>'pdf/grade 2/sem1/القيمة المنزلية.pdf']);
        Lesson::create(['name' => 'العدد الزوجي والعدد الفردي','unit_id' => 9,'description'=>'تعلم الفرق بين الأعداد الزوجية والفردية بطريقة ممتعة','video_url'=>'https://youtu.be/-p3jFmCzVn0?si=BpEY_JJAjYt8mOcF', 'pdf_path'=>'pdf/grade 2/sem1/العدد الزوجي والعدد الفردي.pdf']);
        Lesson::create(['name' => 'الجمع دون حمل ضمن 99','unit_id' => 10,'description'=>'جمع الأرقام بسهولة بدون نقل للمنزلة التالية','video_url'=>'https://youtu.be/cqE8hjvPLFE?si=AdzUibB-T2wstKbq', 'pdf_path'=>'pdf/grade 2/sem1/جمع عددين ضمن 99 دون حمل.pdf']);
        Lesson::create(['name' => 'طرح عددين ضمن 99 دون استلاف','unit_id' => 10,'description'=>'تعلم الطرح دون الحاجة للاستلاف','video_url'=>'https://youtu.be/V4sIrP5DdN0?si=IH0v6jYGEYgT6AtD', 'pdf_path'=>'pdf/grade 2/sem1/طرح عددين ضمن 99 دون استلاف.pdf']);
        Lesson::create(['name' => 'الأعداد ضمن 199','unit_id' => 11,'description'=>'اكتشف الأرقام من 100 حتى 199 بطريقة مبسطة','video_url'=>'https://youtu.be/gmOneJK4cUI?si=S_ozAFCgrVIvR4ol', 'pdf_path'=>'pdf/grade 2/sem1/الاعداد ضمن 199.pdf']);
        Lesson::create(['name' => 'الأعداد ضمن 999','unit_id' => 11,'description'=>'تعرّف على الأرقام من 100 حتى 999 خطوة بخطوة','video_url'=>'https://youtu.be/rwxwZMA8crg?si=GN2m7CAZ-svWKKy2', 'pdf_path'=>'pdf/grade 2/sem1/الاعداد ضمن 999']);
        Lesson::create(['name' => 'القيمة المنزلية للأعداد ضمن 999','unit_id' => 11,'description'=>'فهم مكان الرقم وقيمته ضمن المئات والعشرات والوحدات','video_url'=>'https://youtu.be/KqyT-qdgEO8?si=72rsdM4yxgFEcWW1', 'pdf_path'=>'pdf/grade 2/sem1/القيمة المنزلية للاعداد ضمن 999.pdf']);
        Lesson::create(['name' => 'مقارنة الأعداد ضمن 999','unit_id' => 11,'description'=>'اكتشف أي رقم أكبر وأي رقم أصغر ضمن 999','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 2/sem1/مقارنة الاعداد ضمن 999.pdf']);
        Lesson::create(['name' => 'ترتيب الأعداد ضمن 999','unit_id' => 11,'description'=>'رتب الأرقام من الأصغر للأكبر والعكس بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 2/sem1/ترتيب الاعداد ضمن 999.pdf']);
        Lesson::create(['name' => 'القطعة المستقيمة والخط المنحني','unit_id' => 12, 'description'=>'تعلّم الفرق بين الخطوط المستقيمة والمنحنية بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 2/sem1/القطعة المستقيمة والخط المنحني.pdf']);
        Lesson::create(['name' => 'المربع','unit_id' => 12,'description'=>'اكتشف شكل المربع وخصائصه بطريقة مرحة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 2/sem1/المربع.pdf']);

        Lesson::create(['name' => 'جمع عددين ضمن 999 دون حمل','unit_id' => 13,'description'=>'تعلم جمع الأرقام الكبيرة بدون نقل للمنزلة التالية','video_url'=>'https://youtu.be/ogESnLhLTzU?si=DzpRGfM6mJXJh6Hf', 'pdf_path'=>'pdf/grade 2/sem2/جمع عددين ضمن 999 دون حمل.pdf']);
        Lesson::create(['name' => 'جمع عددين ضمن 999 مع الحمل','unit_id' => 13,'description'=>'تعلم جمع الأرقام الكبيرة مع نقل الرقم للمنزلة التالية','video_url'=>'https://youtu.be/gNa1COw3UxU?si=UJKEpw2_z_CBmvpS', 'pdf_path'=>'pdf/grade 2/sem2/جمع عددين ضمن 999 مع حمل.pdf']);
        Lesson::create(['name' => 'طرح عددين ضمن 999 دون استلاف','unit_id' => 13,'description'=>'اكتشف كيف نطرح الأرقام الكبيرة دون الحاجة للاستلاف','video_url'=>'https://youtu.be/oPb2_gZIYI0?si=p8HxspCJ1obqETid', 'pdf_path'=>'pdf/grade 2/sem2/طرح عددين ضمن 999 دون استلاف.pdf']);
        Lesson::create(['name' => 'العلاقة بين الجمع والطرح','unit_id' => 13,'description'=>'فهم كيف أن الجمع والطرح مرتبطان ببعض بطريقة مبسطة','video_url'=>'https://youtu.be/ADpOQos3Dg4?si=h5-jQPhgS3mtD34Y', 'pdf_path'=>'pdf/grade 2/sem2/العلاقة بين الجمع والطرح ضمن 999.pdf']);
        Lesson::create(['name' => 'طرح عددين ضمن 999 مع الاستلاف','unit_id' => 13,'description'=>'تعلم الطرح للأرقام الكبيرة باستخدام الاستلاف خطوة بخطوة','video_url'=>'https://youtu.be/5hhBZwKNflU?si=V15dPvUYCrJRonwj', 'pdf_path'=>'storage/app/public/pdf/grade 2/sem2/طرح عددين ضمن 999 مع الاستلاف.pdf']);
        Lesson::create(['name' => 'خواص عملية الجمع','unit_id' => 13,'description'=>'اكتشف القوانين الممتعة للجمع مثل التبادلية والتجميعية','video_url'=>'https://youtu.be/1vHA_ejV1V8?si=izLYRZCbi80Vn151', 'pdf_path'=>'pdf/grade 2/sem2/خواص عملية الجمع.pdf']);
        Lesson::create(['name' => 'العد القفزي','unit_id' => 14,'description'=>'تعلم العد بالقفزات لتسريع العد وفهم الأنماط','video_url'=>'https://youtu.be/vNXJeb4uJYo?si=a3lySowMkzqokvlg', 'pdf_path'=>'pdf/grade 2/sem2/العد القفزي.pdf']);
        Lesson::create(['name' => 'مفهوم الضرب','unit_id' => 14,'description'=>'اكتشف الضرب كجمع متكرر بطريقة سهلة وممتعة','video_url'=>'https://youtu.be/QhgcEa8oYj8?si=fvsh7GzvLzYJYUOO', 'pdf_path'=>'pdf/grade 2/sem2/مفهوم الضرب.pdf']);
        Lesson::create(['name' => 'حقائق الضرب لعدد 2','unit_id' => 14,'description'=>'تعلّم جدول ضرب الرقم 2 بسهولة وبطريقة ممتعة','video_url'=>'https://youtu.be/7ijdrmCa1A0?si=-0kuVxQICj-Z8Pkk', 'pdf_path'=>'pdf/grade 2/sem2/حقائق الضرب للعدد 2.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 3','unit_id' => 14,'description'=>'اكتشف جدول ضرب الرقم 3 خطوة بخطوة','video_url'=>'https://youtu.be/yFJfVKH6jMM?si=ULeeXOATKEbe3aJz', 'pdf_path'=>'pdf/grade 2/sem2/حقائق الضرب للعدد 3.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 4','unit_id' => 14,'description'=>'تعلّم جدول ضرب الرقم 4 بطريقة ممتعة وسهلة','video_url'=>'https://youtu.be/19zfBkJpPNY?si=XDWf4Sm_FaU2LeYy', 'pdf_path'=>'pdf/grade 2/sem2/حقائق الضرب للعدد 4.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 5','unit_id' => 14,'description'=>'اكتشف جدول ضرب الرقم 5 بسهولة','video_url'=>'https://youtu.be/815KUdQlm8k?si=Ohvv1xYepQiKezwf', 'pdf_path'=>'pdf/grade 2/sem2/حقائق الضرب للعدد 5.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 10','unit_id' => 14,'description'=>'تعلّم جدول ضرب الرقم 10 بطريقة ممتعة وسريعة','video_url'=>'https://youtu.be/Yl1xgZuHdPs?si=gn0gy2HdkHIksPgh', 'pdf_path'=>'pdf/grade 2/sem2/حقائق الضرب للعدد 10.pdf']);

        Lesson::create(['name' => 'الأعداد ضمن 9999','unit_id' => 15,'description'=>'تعرّف على الأرقام الكبيرة حتى 9999 بطريقة ممتعة وسهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/الأعداد ضمن 9999pdf']);
        Lesson::create(['name' => 'القيمة المنزلية','unit_id' => 15,'description'=>'اكتشف قيمة كل رقم حسب مكانه (الوحدات والعشرات والمئات والألوف)','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/القيمة المنزلية للاعداد ضمن 9999.pdf']);
        Lesson::create(['name' => 'المقارنة بين الأعداد ضمن 9999','unit_id' => 15,'description'=>'تعلم كيف تحدد أي رقم أكبر وأي رقم أصغر ضمن 9999','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/المقارنة بين الاعداد ضمن 9999.pdf']);
        Lesson::create(['name' => 'التقريب','unit_id' => 15, 'description'=>'تعلم كيف نقرب الأرقام لأقرب عشرة أو مئة بطريقة سهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/التقريب.pdf']);
        Lesson::create(['name' => 'جمع عددين ضمن 9999 دون الحمل','unit_id' => 16,'description'=>'تعلم جمع الأرقام الكبيرة بدون نقل للمنزلة التالية','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/جمع عددين ضمن 9999 دون حمل.pdf']);
        Lesson::create(['name' => 'جمع عددين ضمن 9999 مع الحمل','unit_id' => 16,'description'=>'تعلم جمع الأرقام الكبيرة مع نقل الرقم للمنزلة التالية','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/جمع عددين ضمن 9999 مع الحمل.pdf']);
        Lesson::create(['name' => 'طرح عددين ضمن 9999 دون استلاف','unit_id' => 16,'description'=>'تعلم الطرح دون الحاجة للاستلاف للأرقام الكبيرة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/طرح عددين ضمن 9999 دون استلاف.pdf']);
        Lesson::create(['name' => 'طرح عددين ضمن 9999 مع الاستلاف','unit_id' => 16,'description'=>'تعلم الطرح للأرقام الكبيرة باستخدام الاستلاف خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/طرح عددين ضمن 9999 مع الاستلاف.pdf']);
        Lesson::create(['name' => 'الأعداد ضمن 99999','unit_id' => 17,'description'=>'اكتشف الأرقام الكبيرة حتى 99999 بطريقة مبسطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/الاعداد ضمن 99999.pdf']);
        Lesson::create(['name' => 'القيمة المنزلية والصورة الموسعة','unit_id' => 17,'description'=>'اكشف الأرقام الكبيرة وفككها لتفهمها بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/القيمة المنزلية والصورة الموسعة.pdf']);
        Lesson::create(['name' => 'مقارنة الأعداد','unit_id' => 17,'description'=>'اكتشف أي رقم أكبر وأي رقم أصغر بطريقة ممتعة وبسيطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem1/مقارنة الاعداد ضمن 99999.pdf']);

        Lesson::create(['name' => 'التقريب','unit_id' => 18,'description'=>'تعلم كيف نقرب الأرقام الكبيرة لأقرب عشرة أو مئة بطريقة سهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/التقريب2.987pdf']);
        Lesson::create(['name' => 'جمع عددين ضمن 99999 مع الحمل','unit_id' => 18,'description'=>'تعلم جمع الأرقام الكبيرة مع نقل الرقم للمنزلة التالية خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/جمع عددين ضمن 99999 مع الحمل.pdf']);
        Lesson::create(['name' => 'التحقق من عملية الجمع بالتبديل والتقريب','unit_id' => 18,'description'=>'اكتشف طرق التأكد من صحة الجمع باستخدام التبديل والتقريب','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/التحقق من عملية الجمع بالتبديل والتقريب.pdf']);
        Lesson::create(['name' => 'طرح عددين ضمن 99999 دون استلاف','unit_id' => 18,'description'=>'تعلم الطرح للأرقام الكبيرة دون الحاجة للاستلاف','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/طرح عددين ضمن 99999 دون استلاف.pdf']);
        Lesson::create(['name' => 'طرح عددين ضمن 99999 مع الاستلاف','unit_id' => 18,'description'=>'تعلم الطرح للأرقام الكبيرة باستخدام الاستلاف خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/طرح عددين ضمن 99999 مع الاستلاف.pdf']);
        Lesson::create(['name' => 'التحقق من عملية الطرح بالجمع والتقدير','unit_id' => 18,'description'=>'تحقق من صحة الطرح باستخدام الجمع والتقدير بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/التحقق من عملية الطرح بالجمع والتقدير.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 2','unit_id' => 19,'description'=>'تعلم جدول ضرب الرقم 2 بطريقة ممتعة وسهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/حقائق الضرب للعدد 2.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 3','unit_id' => 19,'description'=>'اكتشف جدول ضرب الرقم 3 خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/حقائق الضرب للعدد 3.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 4','unit_id' => 19,'description'=>'تعلم جدول ضرب الرقم 4 بطريقة ممتعة وسهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/حقائق الضرب للعدد 4.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 5','unit_id' => 19, 'description'=>'تعلم جدول ضرب الرقم 5 بسرعة وبشكل ممتع','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/حقائق الضرب للعدد 5.pdf']);
        Lesson::create(['name' => 'خصائص عملية الضرب','unit_id' => 19,'description'=>'اكتشف القوانين الممتعة للضرب مثل التبادلية والتجميعية','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/خصائص عملية الضرب.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 6','unit_id' => 19,'description'=>'تعلم جدول ضرب الرقم 6 بطريقة مبسطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/حقائق الضرب للعدد 6.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 7','unit_id' => 19,'description'=>'اكتشف جدول ضرب الرقم 7 خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/حقائق الضرب للعدد 7.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 8','unit_id' => 19,'description'=>'تعلم جدول ضرب الرقم 8 بسهولة ومتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/حقائق الضرب للعدد 8.pdf']);
        Lesson::create(['name' => 'حقائق الضرب للعدد 9','unit_id' => 19,'description'=>'اكتشف جدول ضرب الرقم 9 بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_pdf/grade 3/sem2/حقائق الضرب للعدد 9.pdf']);
        Lesson::create(['name' => 'الضرب في العشرات أو المئات','unit_id' => 19,'description'=>'تعلم كيف نضرب الأرقام في 10 أو 100 بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/الضرب في العشرات او المئات.pdf']);
        Lesson::create(['name' => 'القسمة 1','unit_id' => 20,'description'=>'تعلم القسمة خطوة بخطوة بطريقة سهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/القسمة1.pdf']);
        Lesson::create(['name' => 'القسمة 2','unit_id' => 20,'description'=>'تعلم القسمة للأرقام الأكبر بأسلوب مبسط','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/القسمة2.pdf']);
        Lesson::create(['name' => 'الكسور','unit_id' => 21,'description'=>'اكتشف مفهوم الكسور بطريقة ممتعة وسهلة للفهم','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/الكسور.pdf']);
        Lesson::create(['name' => 'الكسور المتكافئة','unit_id' => 21,'description'=>'تعلم كيف تكون الكسور متساوية القيمة رغم اختلاف أرقامها','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/الكسور المتكافئة.pdf']);
        Lesson::create(['name' => 'مقارنة الكسور','unit_id' => 21,'description'=>'تعرّف على طريقة مقارنة الكسور لمعرفة أيها أكبر أو أصغر','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/مقارنة الكسور.pdf']);
        Lesson::create(['name' => 'المجسمات','unit_id' => 22,'description'=>'اكتشف الأشكال الثلاثية الأبعاد وخصائصها بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/المجسمات.pdf']);
        Lesson::create(['name' => 'وحدات قياس الكتلة','unit_id' => 22,'description'=>'تعلم كيف نقيس الأشياء بالجرام والكيلوغرام بطريقة سهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/وحدات قياس الكتلة.pdf']);
        Lesson::create(['name' => 'وحدات قياس الزمن','unit_id' => 22,'description'=>'اكتشف قياس الوقت بالدقائق والساعات والأيام','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/وحدات قياس الزمن.pdf']);
        Lesson::create(['name' => 'وحدات قياس الطول','unit_id' => 22,'description'=>'تعلّم قياس الأشياء بالمتر والسنتيمتر بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/وحدات قياس الطول.pdf']);
        Lesson::create(['name' => 'المحيط','unit_id' => 22,'description'=>'اكتشف كيفية حساب محيط الأشكال بطريقة سهلة وممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/المحيط.pdf']);
        Lesson::create(['name' => 'المساحة','unit_id' => 22,'description'=>'تعلم حساب مساحة الأشكال بطريقة بسيطة للطلاب الصغار','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 3/sem2/المساحة.pdf']);

        Lesson::create(['name' => 'الأعداد ضمن 999999','unit_id' => 23,'description'=>'تعرّف على الأرقام الكبيرة حتى 999,999 بطريقة ممتعة وسهلة','video_url'=>'https://www.youtube.com/embed/YHLy3TmPMRs?si=FMcG6h01NKndVX7a', 'pdf_path'=>'pdf/grade 4/sem1/الأعداد ضمن 999999.pdf']);
        Lesson::create(['name' => 'الأعداد الكبيرة','unit_id' => 23,'description'=>'اكتشف الأرقام الكبيرة وفكّر فيها بطريقة بسيطة للطلاب الصغار','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/الاعداد الكبيرة.pdf']);
        Lesson::create(['name' => 'القيمة المنزلية للرقم في الأعداد الكبيرة','unit_id' => 23,'description'=>'فهم قيمة كل رقم حسب مكانه في الأعداد الكبيرة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/القيمة المنزلية للرقم في الاعداد الكبيرة.pdf']);
        Lesson::create(['name' => 'مقارنة الأعداد الكبيرة','unit_id' => 23,'description'=>'تعلّم كيف تعرف أي رقم أكبر أو أصغر بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/مقارنة الاعداد الكبيرة.pdf']);
        Lesson::create(['name' => 'ضرب عدد من منزلتين في عدد من منزلة','unit_id' => 24,'description'=>'تعلم ضرب الأرقام المكونة من منزلتين بطريقة مبسطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/ضرب عدد من منزلتين في عدد من منزلة.pdf']);
        Lesson::create(['name' => 'ضرب عدد من ثلاث منازل في عدد من منزلة','unit_id' => 24,'description'=>'اكتشف كيفية ضرب الأرقام الكبيرة خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/ضرب عدد من 3 منازل في عدد من منزلة.pdf']);
        Lesson::create(['name' => 'قسمة عدد من منزلتين على عدد من منزلة','unit_id' => 24,'description'=>'تعلم القسمة للأرقام المكونة من منزلتين بطريقة سهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/قسمة عدد من منزلتين على عدد من منزلة.pdf']);
        Lesson::create(['name' => 'تقدير ناتج الضرب والقسمة','unit_id' => 24,'description'=>'تعلم كيف تقدّر ناتج الضرب أو القسمة بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/تقدير ناتج الضرب والقسمة.pdf']);
        Lesson::create(['name' => 'الكسور المتكافئة','unit_id' => 25,'description'=>'اكتشف الكسور التي لها نفس القيمة رغم اختلاف أرقامها','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/الكسور المتكافئة.pdf']);
        Lesson::create(['name' => 'مقارنة الكسور','unit_id' => 25,'description'=>'تعلم كيف تعرف أي كسر أكبر أو أصغر بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/مقارنة الكسور.pdf']);
        Lesson::create(['name' => 'جمع الكسور','unit_id' => 25,'description'=>'اكتشف طريقة جمع الكسور خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/جمع الكسور.pdf']);
        Lesson::create(['name' => 'طرح الكسور','unit_id' => 25,'description'=>'تعلم كيفية طرح الكسور بسهولة وبساطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/طرح الكسور.pdf']);
        Lesson::create(['name' => 'العدد الكسري','unit_id' => 25,'description'=>'تعرّف على الأعداد الكسريّة وكيف نقرأها ونكتبها','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/العدد الكسري.pdf']);
        Lesson::create(['name' => 'جمع وطرح الأعداد الكسرية','unit_id' => 25,'description'=>'تعلم الجمع والطرح للأعداد الكسرية بطريقة سهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/جمع وطرح الاعداد الكسرية.pdf']);
        Lesson::create(['name' => 'المستقيمات المتوازية والمتعامدة','unit_id' => 26,'description'=>'اكتشف الفرق بين المستقيمات المتوازية والمتعامدة بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/المستقيمات المتوازية والمتعامدة.pdf']);
        Lesson::create(['name' => 'الزوايا','unit_id' => 26,'description'=>'تعلم أنواع الزوايا وكيف نعرفها بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/الزوايا.pdf']);
        Lesson::create(['name' => 'زوايا المثلث','unit_id' => 26,'description'=>'اكتشف زوايا المثلث وخصائصها بطريقة مبسطة للطلاب','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem1/زوايا المثلث.pdf']);

        Lesson::create(['name' => 'مضاعفات العدد','unit_id' => 27,'description'=>'تعلم العد بالمضاعفات لاكتشاف الأنماط بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/مضاعفات العدد.pdf']);
        Lesson::create(['name' => 'قابلية القسمة على 2','unit_id' => 27,'description'=>'تعلّم كيف تعرف إذا كان الرقم يقبل القسمة على 2 بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/قابلية القسمة على 2.pdf']);
        Lesson::create(['name' => 'قابلية القسمة على 3','unit_id' => 27,'description'=>'اكتشف طريقة معرفة الأرقام التي تقبل القسمة على 3','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/قابلية القسمة على 3.pdf']);
        Lesson::create(['name' => 'قابلية القسمة على 4','unit_id' => 27,'description'=>'تعلّم اختبار القسمة على 4 بطريقة مبسطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/قابلية القسمة على 4.pdf']);
        Lesson::create(['name' => 'قابلية القسمة على 5','unit_id' => 27,'description'=>'اكتشف الأرقام التي تنتهي بـ0 أو 5 لتعرف القسمة على 5','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/قابلية القسمة على 5.pdf']);
        Lesson::create(['name' => 'ضرب عدد من منزلتين في عدد من منزلتين','unit_id' => 28,'description'=>'تعلم ضرب الأرقام الكبيرة خطوة بخطوة بطريقة سهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/ضرب عدد من منزلتين في عدد من منزلتين.pdf']);
        Lesson::create(['name' => 'ضرب عدد من 3 منزل في عدد من منزلتين','unit_id' => 28,'description'=>'اكتشف كيفية ضرب الأرقام الكبيرة بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/ضرب عدد من ثلاث منازل في عدد من منزلتين.pdf']);
        Lesson::create(['name' => 'قسمة عدد من منزلتين على عدد من منزلتين','unit_id' => 28,'description'=>'تعلّم القسمة للأرقام الكبيرة بطريقة مبسطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/قسمة عدد من منزلتين على عدد من منزلتين.pdf']);
        Lesson::create(['name' => 'قسمة عدد من 3 منازل على عدد من منزلتين','unit_id' => 28,'description'=>'تعلم القسمة للأرقام الكبيرة خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/قسمة عدد من ثلاث منازل على عدد من منزلتين.pdf']);
        Lesson::create(['name' => 'الكسور العشرية','unit_id' => 29,'description'=>'تعرف على الكسور العشرية وكيف نقرأها ونكتبها بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/الكسور العشرية.pdf']);
        Lesson::create(['name' => 'الأعداد العشرية','unit_id' => 29,'description'=>'اكتشف الأعداد العشرية واستخدامها بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/الاعداد العشرية.pdf']);
        Lesson::create(['name' => 'جمع الكسور العشرية','unit_id' => 29,'description'=>'تعلم كيفية جمع الكسور العشرية خطوة بخطوة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/جمع الكسور العشرية.pdf']);
        Lesson::create(['name' => 'طرح الكسور العشرية','unit_id' => 29,'description'=>'اكتشف طريقة طرح الكسور العشرية بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/طرح الكسور العشرية.pdf']);
        Lesson::create(['name' => 'جمع الأعداد العشرية','unit_id' => 29,'description'=>'تعلم الجمع للأعداد العشرية بطريقة مبسطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/جمع الاعداد العشرية.pdf']);
        Lesson::create(['name' => 'المربع وخصائصه','unit_id' => 30,'description'=>'اكتشف شكل المربع وميزاته بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/المربع وخصائصه.pdf']);
        Lesson::create(['name' => 'محيط المربع','unit_id' => 30,'description'=>'تعلم كيف تحسب محيط المربع بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/محيط المربع.pdf']);
        Lesson::create(['name' => 'المستطيل وخصائصه','unit_id' => 30,'description'=>'تعرّف على شكل المستطيل وخصائصه بطريقة مبسطة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/المستطيل وخصائصه.pdf']);
        Lesson::create(['name' => 'محيط المستطيل','unit_id' => 30,'description'=>'تعلم حساب محيط المستطيل بطريقة سهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/محيط المستطيل.pdf']);
        Lesson::create(['name' => 'التحويل بين وحدات القياس','unit_id' => 30, 'description'=>'اكتشف كيفية تحويل الأطوال والأوزان والسعات بسهولة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/التحويل بين وحدات القياس.pdf']);
        Lesson::create(['name' => 'حجم متوازي المستطيلات','unit_id' => 30,'description'=>'تعلم حساب حجم متوازي المستطيلات بطريقة ممتعة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/حجم متوازي المستطيلات.pdf']);
        Lesson::create(['name' => 'التجربة العشوائية','unit_id' => 31,'description'=>'تعرف على التجارب العشوائية بطريقة مبسطة للطلاب','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/التجربة العشوائية.pdf']);
        Lesson::create(['name' => 'الفرصة','unit_id' => 31,'description'=>'اكتشف مفهوم الاحتمالات والفرص بطريقة ممتعة وسهلة','video_url'=>'https://www.youtube.com/embed/OP8P5i3_4aA', 'pdf_path'=>'pdf/grade 4/sem2/الفرصة.pdf']);

    }
}
